[package]
name = "codex-utils-home-dir"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
codex-utils-absolute-path = { workspace = true }
dirs = { workspace = true }

[target.'cfg(target_env = "ohos")'.dependencies]
codex-uds = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
